# Generated by Django 5.0.4 on 2024-04-15 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='short_link',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
