# Generated by Django 5.0.4 on 2024-04-15 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortner', '0002_url_short_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='short_link',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
